let languages={
    ar:{
        pref:"الإعدادات",
        occ:"عدد الآيات",
        size:"حجم",
        font:"الخط",
        trans:"الترجمة أو التفسير",
        mark:"إشارة",
        colour:"لون",
        show: "أظهر الكل",
        hide:"أخفي",
        tefsir:"تفسير",
        oneLine:"سطر واحد",
        source:"مصدر",
        language:"لغة",
        close:"أغلق",
        arabic :"عربي",
        turkish:"تركي",
        english:"انكليزي",
        soundSettings:"خيارات الاستماع",
        listening: "يتم تسجيل الصوت"

    },
    tr:{
        pref:"ayarlar",
        occ:"ayet",
        size:"boy",
        font:"font",
        trans:"Meal ya da tefsir",
        mark:"İşaret",
        colour:"renk",
        show:"Hepsi göster",
        hide:"Gizle",
        tefsir:"Tefsir",
        oneLine:"tek satır",
        source:"kaynak",
        language:"dil",
        close:"kapat",
        arabic :"Arapça",
        turkish:"Türkçe",
        english:"İnglizce",
        soundSettings: "Dinleme seçenekleri",
        listening: "Dinliyorum"


    },
    en:{
        pref:"preference",
        occ:"verses",
        size:"size",
        font:"font",
        trans:"Translation",
        mark:"Mark",
        colour:"colour",
        show:"Show All",
        hide:"Hide",
        tefsir:"tefsir",
        oneLine:"One line",
        source:"source",
        language:"language",
        close:"close",
        arabic :"Arabic",
        turkish:"Turkish",
        english:"English",
        soundSettings: "Listening options",
        listening: "lisetning"

    },
}